<script>
    (function () {
        var userTime = new Date();
        if (userTime.getHours() > 10 && userTime.getHours() < 16) {
            document.querySelector('.page').classList.toggle('light');
            document.querySelector('.reading-mode-toggle').classList.toggle('dark');
        }
    })();
</script>

<script>
    !function (e) {
        e.className = e.className.replace(/\bno-js\b/, 'js')
    }(document.documentElement)
</script>
