<?php
/**
 * Copyright © 2019 Denistrator. No rights reserved.
 * bitch
 */
?>

<section class="section education">
    <h3 class="title education-title section-title"><span
                class="lang-ru">Обучение</span> <span class="lang-en">Education</span>
    </h3>
    <p class="desc education-desc"><span class="lang-ru">Приобретённые знания</span>
        <span class="lang-en">What i learned</span>
    </p>
    <p class="education-courses">
        <small class="education-date">11.2016</small>
        <span class="lang-ru">Закончил курс</span> <span class="lang-en">Сompleted the course</span>
        "
        <a href="http://spalah.ua/kh/school/advanced-html-css/">Advanced HTML/CSS</a>"
        <span class="lang-ru">в</span> <span class="lang-en">in</span> <a
                href="http://spalah.ua/kh/school/">Spalah IT-school</a>. <span
                class="lang-ru">Диплом с оценкой 5/5.</span> <span class="lang-en">Graduated with 5/5 score.</span>
        (
        <a href="pub/static/frontend/Denistrator/resume-base/en_US/misc/media/3-FHD-min.png"
           class="lang-ru">Сертификат</a> <a
                href="pub/static/frontend/Denistrator/resume-base/en_US/misc/media/3-FHD-min.png"
                class="lang-en">Certificate</a> <span
                class="line-separator">/</span> <a
                href="pub/static/frontend/Denistrator/resume-base/en_US/misc/media/2-FHD-min.png"
                class="lang-ru">Диплом</a> <a
                href="pub/static/frontend/Denistrator/resume-base/en_US/misc/media/2-FHD-min.png"
                class="lang-en">Diploma</a> )
    </p>
</section>
