<?php
/**
 * Copyright © 2019 Denistrator. No rights reserved.
 * bitch
 */
?>

<section class="section experience">
    <h3 class="title section-title">
        <span class="lang-ru">Опыт</span>
        <span class="lang-en">Experience</span>
    </h3>
    <p class="desc">
        <span class="lang-ru">Использование технологий. Работа в команде</span>
        <span class="lang-en">Using technologies. Team work</span>
    </p>
    <ul class="experience-list">
        <li class="experience-item">
            <span class="lang-ru">Вёрстка HTML/CSS — 4 года.</span>
            <span class="lang-en">HTML/CSS Markup - 4 years.</span>
        </li>
        <li class="experience-item">
            <span class="lang-ru">Работа в команде — 1 год.</span>
            <span class="lang-en">Team work - 1 year.</span>
        </li>
        <li class="experience-item">
            <span class="lang-ru">14+ свёрстанных макетов за время самообучения.</span>
            <span class="lang-en">14+ psd layouts made during self education.</span>
        </li>
        <li class="experience-item">
            <span class="lang-ru">11 свёрстанных макетов за время обучения на курсе</span>
            <span class="lang-en">11 psd layouts made during studying on course</span>
            "<a href="http://spalah.ua/kh/school/advanced-html-css/">Advanced HTML/CSS</a>"
        </li>
    </ul>
    <p>
        <span class="lang-ru">Есть опыт вёрстки под Angular. Сейчас выполняю фронтенд задачи для Magento 1/2.</span>
        <span class="lang-en">Have experience in markup for Angular. Currently developing FE for Magento 1/2.</span>
    </p>
</section>
