<?php
/**
 * Copyright © 2019 Denistrator. No rights reserved.
 * bitch
 */
?>
<?php

use \Denistrator\Theme\Block\Sections\Portfolio;

/**
 * @var Portfolio $block
 */
?>
<?php
$baseUrl = $block->getViewFileUrl('/');

$portfolioItems = $block->getPortfolioItems();
?>
<section class="section portfolio">
    <h3 class="title section-title">
        <span class="lang-ru">Портфолио</span>
        <span class="lang-en">Portfolio</span>
    </h3>
    <p class="desc">
        <span class="lang-ru">Последние работы</span>
        <span class="lang-en">Last works</span>
    </p>
    <div class="portfolio-list-wrap">
        <ul class="portfolio-list">
            <?php foreach ($portfolioItems as $portfolioItem): ?>
                <?= $block
                    ->getChildBlock('portfolio_item')
                    ->setData('portfolio_item', $portfolioItem)
                    ->toHtml() ?>
            <?php endforeach; ?>
            <div class="portfolio-expander icon-double-arrow-down only-js"></div>
        </ul>
    </div>
</section>
