<?php
/**
 * Copyright © 2019 Denistrator. No rights reserved.
 * bitch
 */
?>

<section class="section portfolio">
    <h3 class="title section-title"><span
                class="lang-ru">Портфолио</span> <span class="lang-en">Portfolio</span>
    </h3>
    <p class="desc"><span class="lang-ru">Последние работы</span> <span class="lang-en">Last works</span>
    </p>
    <div class="portfolio-list-wrap">
        <ul class="portfolio-list">
            <li class="portfolio-item">
                <a href="https://www.timberland.co.il/" class="portfolio-link">
                    <div class="portfolio-img-holder"><img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-timberland.svg"
                                alt=""
                                class="portfolio-img hasAlternate"> <img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-timberland_i.svg"
                                alt="" class="portfolio-img portfolio-img-alternateImg">
                    </div>
                    <h4 class="portfolio-title"><span
                                class="lang-ru">Timberland (Израиль)</span>
                        <span class="lang-en">Timberland (Israel)</span>
                    </h4>
                    <span class="portfolio-item-label icon-magento"
                          title="Magento 2 Project">Magento 2 Project</span>
                </a>
            </li>
            <li class="portfolio-item">
                <a href="https://www.nautica.co.il/" class="portfolio-link">
                    <div class="portfolio-img-holder"><img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-nautica.svg"
                                alt=""
                                class="portfolio-img hasAlternate"> <img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-nautica_i.svg"
                                alt=""
                                class="portfolio-img portfolio-img-alternateImg"></div>
                    <h4 class="portfolio-title"><span
                                class="lang-ru">Nautica (Израиль)</span> <span
                                class="lang-en">Nautica (Israel)</span></h4>
                    <span class="portfolio-item-label icon-magento"
                          title="Magento 2 Project">Magento 2 Project</span>
                </a>
            </li>
            <li class="portfolio-item">
                <a href="https://www.layam.com/" class="portfolio-link">
                    <div class="portfolio-img-holder"><img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-layam.png"
                                alt=""
                                class="portfolio-img hasAlternate"> <img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-layam_i.png"
                                alt=""
                                class="portfolio-img portfolio-img-alternateImg"></div>
                    <h4 class="portfolio-title"><span
                                class="lang-ru">Layam Sakal (Израиль)</span>
                        <span class="lang-en">Layam Sakal (Israel)</span>
                    </h4>
                    <span class="portfolio-item-label icon-magento"
                          title="Magento 2 Project">Magento 2 Project</span>
                </a>
            </li>
            <li class="portfolio-item portfolio-collapse-pos">
                <a href="http://denistrator.esy.es/mountains" class="portfolio-link">
                    <div class="portfolio-img-holder"><img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-1.png"
                                alt=""
                                class="portfolio-img"></div>
                    <h4 class="portfolio-title"><span class="lang-ru">Mountains</span>
                        <span class="lang-en">Mountains</span>
                    </h4>
                </a>
                <a href="https://github.com/denistrator/training-01-mountains"
                   class="portfolio-github-link icon-github-logo"
                   title="View on GitHab"></a>
            </li>
            <li class="portfolio-item">
                <a href="http://denistrator.esy.es/modest" class="portfolio-link">
                    <div class="portfolio-img-holder"><img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-2.png"
                                alt=""
                                class="portfolio-img"></div>
                    <h4 class="portfolio-title"><span class="lang-ru">Modest</span>
                        <span class="lang-en">Modest</span>
                    </h4>
                </a>
                <a href="https://github.com/denistrator/spalah-lessons--lesson-8"
                   class="portfolio-github-link icon-github-logo"
                   title="View on GitHab"></a>
            </li>
            <li class="portfolio-item">
                <a href="http://denistrator.esy.es/tajam" class="portfolio-link">
                    <div class="portfolio-img-holder"><img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-3.png"
                                alt=""
                                class="portfolio-img hasAlternate"> <img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-3_i.png"
                                alt=""
                                class="portfolio-img portfolio-img-alternateImg"></div>
                    <h4 class="portfolio-title"><span class="lang-ru">Tajam</span> <span
                                class="lang-en">Tajam</span></h4>
                </a>
                <a href="https://github.com/denistrator/spalah-lessons--lesson-7"
                   class="portfolio-github-link icon-github-logo"
                   title="View on GitHab"></a>
            </li>
            <li class="portfolio-item">
                <a href="http://denistrator.esy.es/yellow_moon" class="portfolio-link">
                    <div class="portfolio-img-holder"><img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-4.png"
                                alt=""
                                class="portfolio-img"></div>
                    <h4 class="portfolio-title"><span class="lang-ru">Yellow Moon</span>
                        <span class="lang-en">Yellow Moon</span>
                    </h4>
                </a>
                <a href="https://github.com/denistrator/spalah-lessons--lesson-6"
                   class="portfolio-github-link icon-github-logo"
                   title="View on GitHab"></a>
            </li>
            <li class="portfolio-item old">
                <a href="http://denistrator.esy.es/naturetour/" class="portfolio-link">
                    <div class="portfolio-img-holder"><img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-no-image.png"
                                alt=""
                                class="portfolio-img hasAlternate"> <img
                                src="pub/static/frontend/Denistrator/resume-base/en_US/images/content/project-no-image_i.png"
                                alt=""
                                class="portfolio-img portfolio-img-alternateImg"></div>
                    <h4 class="portfolio-title"><span class="lang-ru">Naturetour</span>
                        <span class="lang-en">Naturetour</span>
                    </h4>
                </a>
            </li>
            <div class="portfolio-expander icon-double-arrow-down only-js"></div>
        </ul>
    </div>
</section>
