<?php
/**
 * Copyright © 2019 Denistrator. No rights reserved.
 * bitch
 */
?>

<section class="section skills">
    <h3 class="title skills-title section-title">
        <span class="lang-ru">Навыки</span>
        <span class="lang-en">Skills</span>
    </h3>
    <p class="desc skills-desc">
        <span class="lang-ru">Могу, умею, практикую</span>
        <span class="lang-en">Know it, use it</span>
    </p>
    <ul class="skills-list">
        <li class="skills-item">
            <span class="skills-skill">HTML</span>
            <span class="skills-skill">CSS</span></li>
        <li class="skills-item">
            <span class="skills-skill">CSS Animations</span>
            <span class="skills-skill">Transforms</span>
            <span class="skills-skill">Sprites</span>
        </li>
        <li class="skills-item">
            <span class="skills-skill">SCSS</span>
            <span class="skills-skill">LESS</span>
        </li>
        <li class="skills-item">Flexbox</li>
        <li class="skills-item">Bootstrap</li>
        <li class="skills-item">
            <span class="skills-skill">JavaScript</span>
            <span class="skills-skill">jQuery</span>
        </li>
        <li class="skills-item">
            <span class="lang-ru">PHP (базовый уровень)</span>
            <span class="lang-en">PHP (basics)</span>
        </li>
        <li class="skills-item">
            <span class="skills-skill">BEM</span>
            <span class="skills-skill">
                <span class="lang-ru">Модульная вёрстка</span>
                <span class="lang-en">Modular markup</span>
            </span>
        </li>
        <li class="skills-item">
            <span class="skills-skill">Handlebars</span>
            <span class="skills-skill">Jade</span>
        </li>
        <li class="skills-item">
            <span class="skills-skill">NPM</span>
            <span class="skills-skill">Grunt</span>
            <span class="skills-skill">Gulp</span>
        </li>
        <li class="skills-item">Git</li>
        <li class="skills-item">
            <span class="skills-skill">SVG</span>
            <span class="skills-skill">Font Icons</span>
        </li>
        <li class="skills-item">
            <span class="skills-skill">Photoshop</span>
            <span class="skills-skill">Zeplin</span>
            <span class="skills-skill">Avocode</span>
        </li>
        <li class="skills-item">Pixel perfect</li>
        <li class="skills-item">
            <span class="lang-ru">Семантическая вёрстка</span>
            <span class="lang-en">Semantic markup</span>
        </li>
        <li class="skills-item">Jira</li>
        <li class="skills-item">
            <span class="lang-ru">Оптимизация для Google Pagespeed</span>
            <span class="lang-en">Optimization for Google Pagespeed</span>
        </li>
        <li class="skills-item skills-item-special">
            <span class="lang-ru">Английский — грамматика "Pre-intermediate", легко читаю тех. документацию, могу вести переписку.</span>
            <span class="lang-en">English grammar "Pre-Intermediate". Read technical documentation easily, can chat</span>
        </li>
    </ul>
</section>
