<?php
/**
 * Copyright © 2019 Denistrator. No rights reserved.
 * bitch
 */
?>

<div class="container">
    <div class="footer">
        <h5 class="footer-name"><span class="lang-ru">Денис Белевцов</span> <span
                    class="lang-en">Denis Belevtsov</span></h5>
        <a href="mailto:denistrator@yandex.ua" class="footer-mail">denistrator@yandex.ua</a>
        <h5 class="footer-offer"><span class="lang-ru">Открыт для предложений</span> <span class="lang-en">Not open to suggestions</span>
        </h5>
    </div>
</div>
