<?php
/**
 * Copyright © 2019 Denistrator. No rights reserved.
 * bitch
 */
?>

<div class="container">
    <header class="header">
        <div class="header-text">
            <h1 class="header-name">
                <span class="lang-ru">Денис</span>
                <span class="lang-en">Denis</span>
                <span class="lang-ru">Белевцов</span>
                <span class="lang-en">Belevtsov</span>
            </h1>
            <p class="header-pos">
                <span class="lang-ru">Magento Фронт-энд Разработчик</span>
                <span class="lang-en">Magento Front-end Developer</span>
            </p>
        </div>
        <ul class="header-links">
            <li class="header-links-item">
                <a href="mailto:denistrator@yandex.ua" class="header-link icon-mail-black-envelope-symbol">
                    <span class="header-link-text">
                        <span class="only-print">e-mail: </span>denistrator@yandex.ua
                    </span>
                </a>
            </li>
            <li class="header-links-item">
                <a href="tel:+380953182503" class="header-link icon-phone-receiver">
                    <span class="header-link-text">+38 095 318 25 03</span>
                </a>
            </li>
            <li class="header-links-item">
                <a href="skype:denistrator?add" class="header-link icon-skype-logo">
                    <span class="header-link-text">
                        <span class="only-print">skype: </span>denistrator
                    </span>
                </a>
            </li>
            <li class="header-links-item no-print">
                <a href="https://vk.com/denistrator" target="_blank" class="header-link icon-vk"></a>
            </li>
            <li class="header-links-item no-print">
                <a href="https://github.com/denistrator/" target="_blank" class="header-link icon-github-logo"></a>
            </li>
            <li class="header-links-item no-print">
                <a href="https://www.linkedin.com/in/denistrator" target="_blank"
                   class="header-link icon-linkedin-logo"></a>
            </li>
            <li class="header-links-item header-links-item--mobile-open">
                <div class="header-link icon-locate">
                    <span class="header-link-text">
                        <span class="lang-ru">
                            <span class="only-print">г. </span>Харьков</span>
                            <span class="lang-en">Kharkov<span class="only-print"> city</span>
                        </span>
                    </span>
                </div>
            </li>
            <li class="header-links-item no-print">
                <a href="pub/static/frontend/Denistrator/resume-base/en_US/misc/media/Belevtsov Denis - Resume-en.pdf"
                   class="header-link icon-pdf-file-symbol lang-en"></a>
                <a href="pub/static/frontend/Denistrator/resume-base/en_US/misc/media/Belevtsov Denis - Resume-ru.pdf"
                   class="header-link icon-pdf-file-symbol lang-ru"></a>
            </li>
            <li class="header-links-item no-print only-js">
                <button class="reading-mode-toggle header-link icon-sun dark"></button>
            </li>
            <li class="header-links-item no-print only-js">
                <button class="lang-toggle header-link">
                    <strong class="lang-toggle-text">En</strong>
                </button>
            </li>
        </ul>
    </header>
</div>
