<?php
/**
 * Copyright © 2019 Denistrator. No rights reserved.
 * bitch
 */
?>
<?php

use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 */
?>

<div class="content-container">
    <div class="content">
        <div class="content-angled-edge">
            <div class="ver-indents-parent">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="ver-indents-child">
                            <?= $block->getChildHtml('skills') ?>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="ver-indents-child">
                            <?= $block->getChildHtml('education') ?>
                        </div>
                        <div class="ver-indents-child">
                            <?= $block->getChildHtml('experience') ?>
                        </div>
                        <div class="ver-indents-child">
                            <?= $block->getChildHtml('portfolio') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
